# numpy practice session

In [ ]:
#pip install numpy

In [3]:
#import this library in j. notebook
import numpy as np

# Creating an array using numpy

In [5]:
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [7]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [9]:
type(price)

numpy.ndarray

In [11]:
type(food)

numpy.ndarray

In [13]:
len(food)

3

In [15]:
len(price)


3

In [17]:
price[2]

5

In [21]:
price[0:]

array([5, 5, 5])

In [23]:
food[1]

'Samosa'

In [25]:
price.mean()

5.0

In [27]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [39]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
#table of 5
np.arange(5, 55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [51]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [53]:
# specify your data type
np.ones(20, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [55]:
np.ones(50, dtype = np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [5]:
a = np.array([10, 12, 0.4, 20])
a

array([10. , 12. ,  0.4, 20. ])

In [7]:
a.sort()
a

array([ 0.4, 10. , 12. , 20. ])

In [9]:
b = np.array([10.2, 3.4,53.6, 91.6, 45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [13]:
c = np.concatenate((a,b))
c

array([ 0.4, 10. , 12. , 20. , 10.2,  3.4, 53.6, 91.6, 45.5])

# 2-D arrays

In [15]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [17]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [21]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [35]:
a = np.array([[[0,1,2,3],
              [4,5,6,7]],

              [[0,1,2,3],
               [4,5,6,7]],

              [[0,1,2,3],
               [4,5,6,7]]])

a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [37]:
a.ndim

3

In [47]:
type(a)

numpy.ndarray

In [43]:
b = np.array([[5,6,7],
            [8,9,10],
            [11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [45]:
b.ndim

2

In [49]:
#size (number of elements)
a.size

24

In [53]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [51]:
a.shape

(3, 2, 4)

In [59]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
# reshape
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
# reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [67]:
#convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a.shape

(9,)

In [71]:
#row wise
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
b.shape

(1, 9)

In [75]:
#column wise 
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
c.shape

(9, 1)

In [79]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [85]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [88]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
a.sum()

45

In [92]:
a.mean()

5.0